[package]
name = "vulkano-glyph"
description = "Text rendering with vulkano."
version = "0.0.0"
authors = ["Andrew Hickman <andrew.hickman1@sky.com>"]
repository = "https://github.com/andrewhickman/vulkano-glyph"
documentation = "https://docs.rs/vulkano-glyph"
license = "MIT/Apache-2.0"
readme = "README.md"

[dependencies]
vulkano = "0.9.0"
vulkano-shader-derive = "0.9.0"
id-map = "0.2.1"

[dependencies.rusttype]
version = "0.6.1"
features = ["gpu_cache"]

[dev-dependencies]
vulkano-win = "0.9.0"
winit = "0.11.0"